namespace OsuDroid.Game.UI;

public enum UiMaterialIcon
{
    ArrowBack,
    ArrowDropDown,
    Refresh,
    Search,
    Tune,
    PlayArrow,
    Pause,
    Download,
    ChevronRight,
    Check,
    CheckboxBlankOutline,
    Delete,
    Folder,
    Heart,
    HeartOutline,
    Minus,
    Plus,
    Sort,
    Star,
    ViewGridOutline,
    GamepadVariantOutline,
    MonitorDashboard,
    Headphones,
    LibraryMusic,
    GestureTapButton,
    Cogs,
}
