namespace OsuDroid.Game.UI;

public enum UiAction
{
    None,
    MainMenuCookie,
    MainMenuFirst,
    MainMenuSecond,
    MainMenuThird,
    MainMenuVersionPill,
    MainMenuAboutClose,
    MainMenuAboutChangelog,
    MainMenuAboutOsuWebsite,
    MainMenuAboutOsuDroidWebsite,
    MainMenuAboutDiscord,
    MainMenuBeatmapDownloader,
    MainMenuMusicPrevious,
    MainMenuMusicPlay,
    MainMenuMusicPause,
    MainMenuMusicStop,
    MainMenuMusicNext,
    OptionsBack,
    OptionsSectionGeneral,
    OptionsSectionGameplay,
    OptionsSectionGraphics,
    OptionsSectionAudio,
    OptionsSectionLibrary,
    OptionsSectionInput,
    OptionsSectionAdvanced,
    OptionsToggleServerConnection,
    OptionsToggleLoadAvatar,
    OptionsToggleAnnouncements,
    OptionsToggleMusicPreview,
    OptionsToggleShiftPitch,
    OptionsToggleBeatmapSounds,
}
