#!/usr/bin/env python3
from __future__ import annotations

import argparse
import dataclasses
import pathlib
import re
from collections.abc import Iterable

DEFAULT_ROOTS = ("src", "tests")
EXCLUDED_PARTS = {"bin", "obj", "third_party", ".git"}
GENERIC_NAME_PARTS = ("Manager", "Helper", "Utils", "Util", "DataManager", "GlobalManager")
REFERENCE_PORT_PARTS = ("OsuDroid.Game.Beatmaps", "Difficulty", "Reference")
CENTRAL_TOKEN_CATALOGS = {
    pathlib.Path("src/OsuDroid.Game.UI/Assets/DroidAssets.Mods.cs"),
    pathlib.Path("src/OsuDroid.Game.UI/Style/DroidUiColors.cs"),
    pathlib.Path("src/OsuDroid.Game.UI/Style/DroidUiTheme.cs"),
}


@dataclasses.dataclass(frozen=True)
class FileFinding:
    path: pathlib.Path
    logical_lines: int
    type_count: int
    method_count: int
    public_api_count: int
    public_token_count: int
    type_names: tuple[str, ...]
    flags: tuple[str, ...]


def iter_csharp_files(roots: Iterable[str]) -> Iterable[pathlib.Path]:
    for root in roots:
        root_path = pathlib.Path(root)
        if not root_path.exists():
            continue
        for path in root_path.rglob("*.cs"):
            if EXCLUDED_PARTS.intersection(path.parts):
                continue
            yield path


def audit_file(path: pathlib.Path) -> FileFinding:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    logical_lines = sum(1 for line in lines if line.strip() and not line.strip().startswith("//"))
    type_names = tuple(
        match.group(2)
        for match in re.finditer(
            r"^\s*(?:public|internal|private|protected|sealed|static|abstract|partial|readonly|record|file|\s)*\s*"
            r"(class|struct|record|enum|interface)\s+(\w+)",
            text,
            re.MULTILINE,
        )
    )
    method_count = len(
        re.findall(
            r"^\s*(?:public|private|internal|protected|static|sealed|override|virtual|async|readonly|partial)\s+"
            r"(?:[\w<>?,\[\].]+\s+)+(\w+)\s*\(",
            text,
            re.MULTILINE,
        )
    )
    public_lines = re.findall(r"^\s*public\s+.*$", text, re.MULTILINE)
    public_token_count = sum(1 for line in public_lines if re.search(r"\b(const|static\s+readonly)\b", line))
    public_api_count = len(public_lines) - public_token_count
    is_test = "tests" in path.parts
    is_reference_port = all(part in path.parts for part in REFERENCE_PORT_PARTS)
    is_central_token_catalog = path in CENTRAL_TOKEN_CATALOGS
    flags: list[str] = []
    if is_reference_port:
        return FileFinding(
            path,
            logical_lines,
            len(type_names),
            method_count,
            public_api_count,
            public_token_count,
            type_names,
            tuple(),
        )
    if is_central_token_catalog:
        return FileFinding(
            path,
            logical_lines,
            len(type_names),
            method_count,
            public_api_count,
            public_token_count,
            type_names,
            tuple(),
        )
    if logical_lines > 300:
        flags.append("god-file:candidate")
    if len(type_names) > 4:
        flags.append("too-many-types")
    if method_count > 25:
        flags.append("too-many-methods")
    if public_api_count > 30 and not is_test:
        flags.append("wide-public-surface")
    if public_token_count > 30:
        flags.append("public-token-catalog")
    if any(part in path.name for part in GENERIC_NAME_PARTS):
        flags.append("generic-file-name")
    return FileFinding(
        path,
        logical_lines,
        len(type_names),
        method_count,
        public_api_count,
        public_token_count,
        type_names,
        tuple(flags),
    )


def render_markdown(findings: list[FileFinding]) -> str:
    flagged = [finding for finding in findings if finding.flags]
    lines = [
        "# Architecture Audit",
        "",
        "Generated by `scripts/dev/architecture_audit.py`.",
        "",
        "## Summary",
        f"- Files scanned: {len(findings)}",
        f"- Flagged files: {len(flagged)}",
        "",
        "## Flagged files",
        "",
        "| File | LOC | Types | Methods | Public API | Public tokens | Flags | Primary types |",
        "| --- | ---: | ---: | ---: | ---: | ---: | --- | --- |",
    ]
    for finding in sorted(flagged, key=lambda value: (-value.logical_lines, str(value.path))):
        lines.append(
            f"| `{finding.path}` | {finding.logical_lines} | {finding.type_count} | "
            f"{finding.method_count} | {finding.public_api_count} | {finding.public_token_count} | "
            f"{', '.join(finding.flags)} | "
            f"{', '.join(finding.type_names[:6])} |"
        )
    lines.extend([
        "",
        "## Thresholds",
        "- `god-file:candidate`: >300 non-comment logical lines.",
        "- `too-many-types`: >4 type declarations in one file.",
        "- `too-many-methods`: >25 method declarations in one file.",
        "- `wide-public-surface`: >30 non-token public declarations in one source file.",
        "- `public-token-catalog`: >30 public constants/static-readonly tokens in one file.",
        "- Test files can still report god-file and method-count findings, but public test methods are not treated as API surface.",
        "- `src/OsuDroid.Game.Beatmaps/Difficulty/Reference` is a source-provenance port and is counted but not flagged by shape rules.",
        "- Central UI token catalogs are counted but not flagged; they are the intended replacement for scene-local constants.",
    ])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit C# source layout for god-file and ownership smells.")
    parser.add_argument("--format", choices=("markdown",), default="markdown")
    parser.add_argument("--write", type=pathlib.Path, help="Write report to this path.")
    args = parser.parse_args()

    findings = [audit_file(path) for path in sorted(iter_csharp_files(DEFAULT_ROOTS))]
    report = render_markdown(findings)
    if args.write is not None:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(report, encoding="utf-8")
    print(report, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
