namespace OsuDroid.Game.UI.Assets;

public static partial class DroidAssets
{
    public static IReadOnlyList<UiAssetEntry> Catalog => s_assetCatalog;

    private static readonly UiAssetEntry[] s_assetCatalog =
    [
        Texture(MenuBackground, "assets/droid/main-menu/background.png", 1500, 768),
        Texture(EmptyAvatar, "assets/droid/common/empty-avatar.png", 90, 90),
        Texture(BeatmapDownloader, "assets/droid/main-menu/beatmap-downloader-tab.png", 80, 284),
        Texture(Logo, "assets/droid/main-menu/logo.png", 540, 540),
        Texture(Play, "assets/droid/main-menu/play-button.png", 586, 92),
        Texture(Solo, "assets/droid/main-menu/solo-button.png", 586, 92),
        Texture(Options, "assets/droid/main-menu/options-button.png", 586, 92),
        Texture(Multi, "assets/droid/main-menu/multiplayer-button.png", 586, 92),
        Texture(Exit, "assets/droid/main-menu/exit-button.png", 586, 92),
        Texture(Back, "assets/droid/main-menu/back-button.png", 583, 89),
        Texture(MusicPrevious, "assets/droid/main-menu/music-previous.png", 64, 62),
        Texture(MusicPlay, "assets/droid/main-menu/music-play.png", 60, 62),
        Texture(MusicPause, "assets/droid/main-menu/music-pause.png", 66, 66),
        Texture(MusicStop, "assets/droid/main-menu/music-stop.png", 66, 66),
        Texture(MusicNext, "assets/droid/main-menu/music-next.png", 64, 62),
        Texture(MusicNowPlaying, "assets/droid/main-menu/now-playing-panel.png", 1364, 60),
        Texture(SettingsArrowBack, "assets/droid/settings/arrow-back.png", 192, 192),
        Texture(SettingsGeneral, "assets/droid/settings/category-general.png", 192, 192),
        Texture(SettingsGameplay, "assets/droid/settings/category-gameplay.png", 192, 192),
        Texture(SettingsGraphics, "assets/droid/settings/category-graphics.png", 192, 192),
        Texture(SettingsAudio, "assets/droid/settings/category-audio.png", 192, 192),
        Texture(SettingsLibrary, "assets/droid/settings/category-library.png", 192, 192),
        Texture(SettingsInput, "assets/droid/settings/category-input.png", 192, 192),
        Texture(SettingsAdvanced, "assets/droid/settings/category-advanced.png", 192, 192),
        Texture(SettingsCheck, "assets/droid/settings/check.png", 192, 192),
        Texture(SettingsArrowDropDown, "assets/droid/settings/arrow-drop-down.png", 192, 192),
        Texture(BeatmapDownloaderOsuDirect, "assets/droid/beatmap-downloader/osudirect.png", 96, 96),
        Texture(BeatmapDownloaderCatboy, "assets/droid/beatmap-downloader/catboy.png", 96, 96),
        Texture(SongSelectTop, "assets/droid/common/songselect-top.png", 2560, 378),
        Texture(SongSelectButtonBackground, "assets/droid/main-menu/button-background.png", 724, 127),
        Texture(SongSelectBack, "assets/droid/main-menu/back.png", 125, 125),
        Texture(SongSelectMods, "assets/droid/song-select/mods.png", 74, 74),
        Texture(SongSelectModsOver, "assets/droid/song-select/mods-over.png", 74, 74),
        Texture(SongSelectOptions, "assets/droid/song-select/options.png", 74, 74),
        Texture(SongSelectOptionsOver, "assets/droid/song-select/options-over.png", 74, 74),
        Texture(SongSelectRandom, "assets/droid/song-select/random.png", 74, 74),
        Texture(SongSelectRandomOver, "assets/droid/song-select/random-over.png", 74, 74),
        Texture(SongSelectStar, "assets/droid/common/star.png", 46, 47),
        Texture(CommonBackArrow, "assets/droid/common/back-arrow.png", 96, 96),
        Texture(CommonTune, "assets/droid/common/tune.png", 96, 96),
        Texture(CommonBackspace, "assets/droid/common/backspace.png", 96, 96),
        Texture(CommonSearchSmall, "assets/droid/common/search-small.png", 96, 96),
        Texture(CommonSettings, "assets/droid/common/settings.png", 96, 96),

        Texture(ModNoFail, "assets/droid/song-select/mod-nofail.png", 68, 66),
        Texture(ModEasy, "assets/droid/song-select/mod-easy.png", 68, 66),
        Texture(ModReallyEasy, "assets/droid/song-select/mod-reallyeasy.png", 68, 66),
        Texture(ModHalfTime, "assets/droid/song-select/mod-halftime.png", 68, 66),
        Texture(ModHardRock, "assets/droid/song-select/mod-hardrock.png", 68, 66),
        Texture(ModSuddenDeath, "assets/droid/song-select/mod-suddendeath.png", 68, 66),
        Texture(ModPerfect, "assets/droid/song-select/mod-perfect.png", 68, 66),
        Texture(ModHidden, "assets/droid/song-select/mod-hidden.png", 68, 66),
        Texture(ModDoubleTime, "assets/droid/song-select/mod-doubletime.png", 68, 66),
        Texture(ModNightcore, "assets/droid/song-select/mod-nightcore.png", 68, 66),
        Texture(ModFlashlight, "assets/droid/song-select/mod-flashlight.png", 68, 66),
        Texture(ModPrecise, "assets/droid/song-select/mod-precise.png", 68, 66),
        Texture(ModTraceable, "assets/droid/song-select/mod-traceable.png", 68, 66),
        Texture(ModSmallCircle, "assets/droid/song-select/mod-approachdifferent.png", 68, 66),
        Texture(ModRelax, "assets/droid/song-select/mod-relax.png", 68, 66),
        Texture(ModAutopilot, "assets/droid/song-select/mod-relax2.png", 68, 66),
        Texture(ModAutoplay, "assets/droid/song-select/mod-autoplay.png", 68, 66),
        Texture(ModCustomSpeed, "assets/droid/song-select/mod-customspeed.png", 68, 66),
        Texture(ModDifficultyAdjust, "assets/droid/song-select/mod-difficultyadjust.png", 68, 66),
        Texture(ModMirror, "assets/droid/song-select/mod-mirror.png", 68, 66),
        Texture(ModRandom, "assets/droid/song-select/mod-random.png", 68, 66),
        Texture(ModScoreV2, "assets/droid/song-select/mod-scorev2.png", 68, 66),
        Texture(ModMuted, "assets/droid/song-select/mod-muted.png", 68, 66),
        Texture(ModFreezeFrame, "assets/droid/song-select/mod-freezeframe.png", 68, 66),
        Texture(ModWindUp, "assets/droid/song-select/mod-windup.png", 68, 66),
        Texture(ModWindDown, "assets/droid/song-select/mod-winddown.png", 68, 66),
        Texture(ModApproachDifferent, "assets/droid/song-select/mod-approachdifferent.png", 68, 66),
        Texture(ModSynesthesia, "assets/droid/song-select/mod-synesthesia.png", 68, 66),
        Texture(RankingDisabled, "assets/droid/ranking/ranking-disabled.png", 50, 50),
        Texture(RankingEnabledScore, "assets/droid/ranking/ranking-enabled-score.png", 50, 50),
        Texture(RankingEnabledPerformance, "assets/droid/ranking/ranking-enabled-pp.png", 50, 50),
        Texture(SelectionRanked, "assets/droid/common/selection-ranked.png", 50, 50),
        Texture(SelectionApproved, "assets/droid/common/selection-approved.png", 50, 50),
        Texture(SelectionLoved, "assets/droid/common/selection-loved.png", 50, 50),
        Texture(SelectionQuestion, "assets/droid/common/selection-question.png", 50, 50),
        Texture(RankingASmall, "assets/droid/ranking/a-small.png", 30, 30),
        Texture(Loading, "assets/droid/gameplay/loading.png", 212, 212),
        Texture(LoadingTitle, "assets/droid/gameplay/loading-title.png", 1366, 75),
        Texture(Welcome, "assets/droid/gameplay/welcome.png", 375, 78),
        Texture(DevBuildOverlay, "assets/droid/common/dev-build-overlay.png", 512, 3),
    ];
}
